### ISSUE TITLE
Screen freeze when creating a publisher 

### ISSUE THREAD

**Issue by badarovska** [opentok/opentok-ios-sdk-samples#273]
In the latest version of the iOS SDK (v2.24.0) when initializing the publisher, the screen freezes and becomes unresponsive for a few seconds. 

In the previous versions, there was a thread warning when initializing the publisher that has been fixed with the latest one. 
Related issue: https://github.com/opentok/opentok-ios-sdk-samples/issues/267

Since the fix, the thread warning no longer appears, however the screen freeze still remains and now it is more noticeable than before. Now it takes about 10s for the publisher stream be initialized, and in that time the screen is not responsive. In the previous versions, despite the thread warning the freeze and init time was about 2-3s.

**Comment by v-kpheng** [comment]
@badarovska, thanks for letting us know about this issue.  We have a fix in mind and it's scheduled for release next week: https://jira.vonage.com/browse/OPENTOK-49706.

**Comment by beHaze** [comment]
Fixed in v2.24.1

**Comment by badarovska** [comment]
The issue still remains. After the latest fix, the freeze is still only a few seconds, but still there. I even got some 0x8badf00d crashes due to the app unresponsiveness when the publisher is initialized.

**Comment by v-kpheng** [comment]
> The issue still remains. After the latest fix, the freeze is still only a few seconds, but still there. I even got some 0x8badf00d crashes due to the app unresponsiveness when the publisher is initialized.

@badarovska, can you try again please?  Other users tell us it worked for them.  Also, can you provide logs please?
