### ISSUE TITLE
Crash after closing video call

### ISSUE THREAD

**Issue by ve-sdk-ios** [opentok/opentok-ios-sdk-samples#304]
**Describe the bug**
Crash appears after several starting and closing the call in our app. Crash reproduces on iPhone 12 iOS 17.2.1(several devices) and not reproduced on iPhone X iOS 16.7.1. 

**To Reproduce**
I reproduce this crash in our fork from this repo: https://github.com/ve-sdk-ios/opentok-ios-sdk-samples. There is additional start screen with button "Start call" and "Close" button at existing ViewController screen. Action at "Start call" opens yours controller in Video-Transformers sample

1. Push button "Start call"
2. Wait until preview appears
3. Push button "Close"
4. Wait until camera and micro lights disappear (green and orange circle in status bar).
5. Repeat steps

After several times it can be like 3-5 or more the crash appears.

**Expected behavior**
Crash should not be exists

**Screenshots**
<img width="620" alt="Screenshot 2024-01-05 at 14 27 18" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/73183216/cdaacd61-0e86-4f18-88e5-4c6ca959b5f0">
<img width="626" alt="Screenshot 2024-01-05 at 14 27 26" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/73183216/69735e6c-1374-4250-8b57-ef4803a8cf3a">

**Device (please compete the following information):**
- sessionId, if applicable: 1_MX40NzUyMTY1MX5-MTcwNDQ0NzM0MjUxNH53cHBYMSs0eDFER0JvQ0c0TzVLU3M3UHl-fn4
- iOS SDK version:  17.2.1
- OS and version: MacOS Sonoma 14.1.2 (23B92)
- OpenTok 2.27.0

**Additional context**
In our app we have got similar issue but stack trace is different. We have tried to disconnect session before closing the view but it wouldn't help
![292511111-b9d1776a-d1e7-4458-a071-14d850a8f7fd](https://github.com/opentok/opentok-ios-sdk-samples/assets/73183216/e30a60f7-2520-43c2-b7e7-dad078f7a7a5)

**Comment by juliobecerragomez** [comment]
Hello @ve-sdk-ios, can you provide a detailed stack trace? Just using `bt all` in xcode debug console. cc @IGitGotIt

**Comment by ve-sdk-ios** [comment]
`(lldb) bt all
  thread #1, queue = 'com.apple.main-thread'
    frame #0: 0x00000001d76c1178 libsystem_kernel.dylib`mach_msg2_trap + 8
    frame #1: 0x00000001d76c0f10 libsystem_kernel.dylib`mach_msg2_internal + 80
    frame #2: 0x00000001989dda9c IOKit`io_connect_method + 524
    frame #3: 0x00000001989dd828 IOKit`IOConnectCallMethod + 176
    frame #4: 0x00000002065c8c58 IOGPU`ioGPUCommandQueueFinalize + 192
    frame #5: 0x000000018ff9a120 CoreFoundation`_CFRelease + 292
    frame #6: 0x00000002065be6a0 IOGPU`-[IOGPUMetalCommandQueue dealloc] + 40
    frame #7: 0x00000002290f3f34 AGXMetalA14`-[AGXA14FamilyCommandQueue dealloc] + 92
    frame #8: 0x0000000222cce0a0 MetalTools`-[MTLToolsObject dealloc] + 64
    frame #9: 0x0000000222cadfac MetalTools`-[MTLToolsCommandQueue dealloc] + 84
    frame #10: 0x0000000188309374 libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 116
    frame #11: 0x000000018830909c libobjc.A.dylib`objc_destructInstance + 80
    frame #12: 0x000000018830903c libobjc.A.dylib`_objc_rootDealloc + 80
    frame #13: 0x0000000105cf1aec GPUToolsCapture`-[CaptureMTLCommandQueue dealloc] + 248
    frame #14: 0x0000000102165e60 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 51936
    frame #15: 0x0000000188309374 libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 116
    frame #16: 0x000000018830909c libobjc.A.dylib`objc_destructInstance + 80
    frame #17: 0x000000018830903c libobjc.A.dylib`_objc_rootDealloc + 80
    frame #18: 0x00000001021710a8 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 97576
    frame #19: 0x000000018ff99cd0 CoreFoundation`__RELEASE_OBJECTS_IN_THE_ARRAY__ + 116
    frame #20: 0x000000018ff99c0c CoreFoundation`-[__NSArrayM dealloc] + 148
    frame #21: 0x0000000188306b74 libobjc.A.dylib`AutoreleasePoolPage::releaseUntil(objc_object**) + 196
    frame #22: 0x0000000188306a10 libobjc.A.dylib`objc_autoreleasePoolPop + 260
    frame #23: 0x0000000192237cd8 UIKitCore`-[UIView dealloc] + 1004
    frame #24: 0x0000000188306b74 libobjc.A.dylib`AutoreleasePoolPage::releaseUntil(objc_object**) + 196
    frame #25: 0x0000000188306a10 libobjc.A.dylib`objc_autoreleasePoolPop + 260
    frame #26: 0x000000018ffc2a54 CoreFoundation`_CFAutoreleasePoolPop + 32
    frame #27: 0x000000018ffc293c CoreFoundation`__CFRunLoopPerCalloutARPEnd + 48
    frame #28: 0x000000018ffc1d50 CoreFoundation`__CFRunLoopRun + 2036
    frame #29: 0x000000018ffc1478 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #30: 0x00000001d351a4f8 GraphicsServices`GSEventRunModal + 164
    frame #31: 0x00000001923e562c UIKitCore`-[UIApplication _run] + 888
    frame #32: 0x00000001923e4c68 UIKitCore`UIApplicationMain + 340
    frame #33: 0x00000001021592ec Video-Transformers`main(argc=<unavailable>, argv=<unavailable>) at main.m:16:16 [opt]
    frame #34: 0x00000001b2ce6dcc dyld`start + 2240
  thread #10, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x00000001d76c1178 libsystem_kernel.dylib`mach_msg2_trap + 8
    frame #1: 0x00000001d76c0f10 libsystem_kernel.dylib`mach_msg2_internal + 80
    frame #2: 0x00000001d76c0e28 libsystem_kernel.dylib`mach_msg_overwrite + 436
    frame #3: 0x00000001d76c0c68 libsystem_kernel.dylib`mach_msg + 24
    frame #4: 0x000000018ffc3b1c CoreFoundation`__CFRunLoopServiceMachPort + 160
    frame #5: 0x000000018ffc1a14 CoreFoundation`__CFRunLoopRun + 1208
    frame #6: 0x000000018ffc1478 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #7: 0x000000018ef5448c Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
    frame #8: 0x000000018ef8174c Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 64
    frame #9: 0x00000001923474a8 UIKitCore`-[UIEventFetcher threadMain] + 420
    frame #10: 0x000000018efd7de0 Foundation`__NSThread__start__ + 732
    frame #11: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #11
    frame #0: 0x00000001d76cef0c libsystem_kernel.dylib`kevent + 8
    frame #1: 0x0000000102245edc Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 969564
    frame #2: 0x0000000102241f34 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 953268
    frame #3: 0x00000001021cadb4 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 465460
    frame #4: 0x000000010217f174 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 155124
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #12
    frame #0: 0x00000001d76c1b1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001f9f72fd4 libsystem_pthread.dylib`_pthread_cond_wait + 1228
    frame #2: 0x000000010224c87c Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 996604
    frame #3: 0x0000000102247488 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 975112
    frame #4: 0x000000010224c4f8 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 995704
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #13
    frame #0: 0x00000001d76c1b1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001f9f72fd4 libsystem_pthread.dylib`_pthread_cond_wait + 1228
    frame #2: 0x000000010224c87c Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 996604
    frame #3: 0x0000000102247488 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 975112
    frame #4: 0x000000010224c4f8 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 995704
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #14
    frame #0: 0x00000001d76c1b1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001f9f72fd4 libsystem_pthread.dylib`_pthread_cond_wait + 1228
    frame #2: 0x000000010224c87c Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 996604
    frame #3: 0x0000000102247488 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 975112
    frame #4: 0x000000010224c4f8 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 995704
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #15
    frame #0: 0x00000001d76c1b1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001f9f72fd4 libsystem_pthread.dylib`_pthread_cond_wait + 1228
    frame #2: 0x000000010224c87c Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 996604
    frame #3: 0x0000000102247488 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 975112
    frame #4: 0x000000010224c4f8 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 995704
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #20, name = 'caulk.messenger.shared:21'
    frame #0: 0x00000001d76c10f4 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001fcbdc694 caulk`caulk::semaphore::timed_wait(double) + 212
    frame #2: 0x00000001fcbdc4c4 caulk`caulk::concurrent::details::worker_thread::run() + 36
    frame #3: 0x00000001fcbf573c caulk`void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
    frame #4: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #21, name = 'caulk.messenger.shared:high'
    frame #0: 0x00000001d76c10f4 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001fcbdc694 caulk`caulk::semaphore::timed_wait(double) + 212
    frame #2: 0x00000001fcbdc4c4 caulk`caulk::concurrent::details::worker_thread::run() + 36
    frame #3: 0x00000001fcbf573c caulk`void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
    frame #4: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #22, name = 'caulk::deferred_logger'
    frame #0: 0x00000001d76c10f4 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001fcbdc694 caulk`caulk::semaphore::timed_wait(double) + 212
    frame #2: 0x00000001fcbdc4c4 caulk`caulk::concurrent::details::worker_thread::run() + 36
    frame #3: 0x00000001fcbf573c caulk`void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
    frame #4: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #202, queue = 'com.apple.figcapturesource.deadserver-notifications'
    frame #0: 0x00000001d76c10f4 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001058c725c libdispatch.dylib`_dispatch_sema4_wait + 28
    frame #2: 0x00000001058c790c libdispatch.dylib`_dispatch_semaphore_wait_slow + 132
    frame #3: 0x000000010541b674 libRPAC.dylib`interposed_dispatch_semaphore_wait + 164
    frame #4: 0x00000001ac7c1d70 AVFCapture`-[AVCaptureSession _handleCaptureServerConnectionDiedNotification] + 56
    frame #5: 0x000000018ffbd2c4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 128
    frame #6: 0x000000018ffbcca0 CoreFoundation`___CFXRegistrationPost_block_invoke + 88
    frame #7: 0x000000018ffbcbe8 CoreFoundation`_CFXRegistrationPost + 440
    frame #8: 0x000000018ffbc138 CoreFoundation`_CFXNotificationPost + 724
    frame #9: 0x000000018ef527a4 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 92
    frame #10: 0x000000018ffbd2c4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 128
    frame #11: 0x000000018ffbcca0 CoreFoundation`___CFXRegistrationPost_block_invoke + 88
    frame #12: 0x000000018ffbcbe8 CoreFoundation`_CFXRegistrationPost + 440
    frame #13: 0x000000018ffbc138 CoreFoundation`_CFXNotificationPost + 724
    frame #14: 0x000000018ffbbe2c CoreFoundation`CFNotificationCenterPostNotificationWithOptions + 140
    frame #15: 0x00000001058c4f50 libdispatch.dylib`_dispatch_call_block_and_release + 32
    frame #16: 0x00000001058c6b34 libdispatch.dylib`_dispatch_client_callout + 20
    frame #17: 0x00000001058ce98c libdispatch.dylib`_dispatch_lane_serial_drain + 832
    frame #18: 0x00000001058cf728 libdispatch.dylib`_dispatch_lane_invoke + 408
    frame #19: 0x00000001058dc5f8 libdispatch.dylib`_dispatch_root_queue_drain_deferred_wlh + 328
    frame #20: 0x00000001058dbc2c libdispatch.dylib`_dispatch_workloop_worker_thread + 444
    frame #21: 0x00000001f9f73964 libsystem_pthread.dylib`_pthread_wqthread + 288
  thread #227
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #235
    frame #0: 0x00000001f9f739fc libsystem_pthread.dylib`start_wqthread
  thread #243, name = 'com.apple.coremedia.sharedRootQueue.47'
    frame #0: 0x00000001d76c110c libsystem_kernel.dylib`semaphore_timedwait_trap + 8
    frame #1: 0x00000001058c72d8 libdispatch.dylib`_dispatch_sema4_timedwait + 64
    frame #2: 0x00000001058c78d4 libdispatch.dylib`_dispatch_semaphore_wait_slow + 76
    frame #3: 0x00000001058daaa0 libdispatch.dylib`_dispatch_worker_thread + 364
    frame #4: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
* thread #244, queue = 'com.apple.root.user-initiated-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x7b8afadb0)
  * frame #0: 0x000000018830730c libobjc.A.dylib`objc_release + 16
    frame #1: 0x00000001f9f6f438 libsystem_blocks.dylib`_call_dispose_helpers_excp + 48
    frame #2: 0x00000001f9f6f3ec libsystem_blocks.dylib`_Block_release + 252
    frame #3: 0x00000001058c6b34 libdispatch.dylib`_dispatch_client_callout + 20
    frame #4: 0x00000001058daf0c libdispatch.dylib`_dispatch_root_queue_drain + 968
    frame #5: 0x00000001058db6cc libdispatch.dylib`_dispatch_worker_thread2 + 188
    frame #6: 0x00000001f9f73928 libsystem_pthread.dylib`_pthread_wqthread + 228
  thread #245, name = 'com.apple.coremedia.sharedRootQueue.47'
    frame #0: 0x00000001d76c110c libsystem_kernel.dylib`semaphore_timedwait_trap + 8
    frame #1: 0x00000001058c72d8 libdispatch.dylib`_dispatch_sema4_timedwait + 64
    frame #2: 0x00000001058c78d4 libdispatch.dylib`_dispatch_semaphore_wait_slow + 76
    frame #3: 0x00000001058daaa0 libdispatch.dylib`_dispatch_worker_thread + 364
    frame #4: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
  thread #247
    frame #0: 0x00000001f9f739fc libsystem_pthread.dylib`start_wqthread
  thread #248
    frame #0: 0x00000001f9f739fc libsystem_pthread.dylib`start_wqthread
  thread #249, queue = 'com.apple.root.user-initiated-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x7b8afadb0)
    frame #0: 0x000000018830730c libobjc.A.dylib`objc_release + 16
    frame #1: 0x00000001f9f6f438 libsystem_blocks.dylib`_call_dispose_helpers_excp + 48
    frame #2: 0x00000001f9f6f3ec libsystem_blocks.dylib`_Block_release + 252
    frame #3: 0x00000001058c6b34 libdispatch.dylib`_dispatch_client_callout + 20
    frame #4: 0x00000001058daf0c libdispatch.dylib`_dispatch_root_queue_drain + 968
    frame #5: 0x00000001058db6cc libdispatch.dylib`_dispatch_worker_thread2 + 188
    frame #6: 0x00000001f9f73928 libsystem_pthread.dylib`_pthread_wqthread + 228
  thread #251
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #252
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #253
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #254
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #255
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #256
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #257
    frame #0: 0x00000001f9f739fc libsystem_pthread.dylib`start_wqthread
  thread #258
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #259
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #260
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #261
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #262
    frame #0: 0x00000001d76c96d0 libsystem_kernel.dylib`__workq_kernreturn + 8`

**Comment by ve-sdk-ios** [comment]
There is full console output with `bt all`
[stacktrace.txt](https://github.com/opentok/opentok-ios-sdk-samples/files/13886299/stacktrace.txt)

**Comment by IGitGotIt** [comment]
I could not reproduce it. I tried your code and went through the steps 3 X 5+ times (publish only). 
Then I did it once with self subscribe. No luck. 
Maybe I am missing something.

Anyway one suggestion would be to un-publish when the call is closed  and do a dismiss on 
```objc
- (IBAction)closeAction:(id)sender {
  [_session unpublish:_publisher error:nil];
  }
- (void)publisher:(OTPublisherKit*)publisher
  streamDestroyed:(OTStream *)stream {
  [self dismissViewControllerAnimated:YES completion:nil];
}


```
Hopefully that will free up the camera in time for the next sequence of Start. Let me know if that helps. 

Also from the logs I see

```objc
thread #11
    frame #0: 0x00000001d76cef0c libsystem_kernel.dylib`kevent + 8
    frame #1: 0x0000000102245edc Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 969564
    frame #2: 0x0000000102241f34 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 953268
    frame #3: 0x00000001021cadb4 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 465460
    frame #4: 0x000000010217f174 Video-Transformers`-[OTSubscriber initWithStream:delegate:] + 155124
    frame #5: 0x00000001f9f744d4 libsystem_pthread.dylib`_pthread_start + 136
```

Are there subscribers involved?  

I will keep on trying to repo.   I tested on iPhone 12 Pro/ 17.1.2 btw.

**Comment by ve-sdk-ios** [comment]
I tested without subscribers. I have updated the our fork with your recommendation [here](https://github.com/ve-sdk-ios/opentok-ios-sdk-samples.). Still crashed but something new. In unpublish I have got sometimes I got error `(OTSessionErrorDomain error 1011.)` See the new stacktrace 
[stacktrace2.txt](https://github.com/opentok/opentok-ios-sdk-samples/files/13897788/stacktrace2.txt)

**Comment by IGitGotIt** [comment]
In your logs what is 
1) FigCaptureSourceRemote (as the `Capture session runtime error` follows those logs)
2) Why are we seeing `[OTSubscriber initWithStream:delegate:]` when there are no subscribers in the test setup

Will it be possible to try a `session disconnect` on `Close` and then dismissing the modal on `sessionDidDisconnect` instead of publisher `streamDestroyed`. Let's follow the life cycle the whole way. 

Lastly will it be possible to just not use the modal controller and just do the publisher on the main view like it was initially in that sample. That will sort of narrow down the cause of the crash (big if...)

**Comment by ve-sdk-ios** [comment]
1. It is logs from yours SDK. I added only start screen and logic to dismiss the call screen.
2. As you can see in logs there is not any "session streamCreated" logs. So I have no Idea why we are seeing this in stacktrace.

I refactored fork with your instructions and it still crashes.
[stacktrace4.txt](https://github.com/opentok/opentok-ios-sdk-samples/files/13916521/stacktrace4.txt)

It is our use case. User can start the live stream and finish them. And after that start a live stream again. We are expected that all will work without crashes.

**Comment by ve-sdk-ios** [comment]
@IGitGotIt  @juliobecerragomez  Did you fix something on your side? I can't see anymore logs 

`<<<< FigCaptureSourceRemote >>>> Fig assert: "! storage->connectionDied" at bail (FigCaptureSourceRemote.m:235) - (err=0)
<<<< FigCaptureSourceRemote >>>> Fig assert: "err == 0 " at bail (FigCaptureSourceRemote.m:253) - (err=18 446 744 073 709 535 163)
<<<< FigCaptureSourceRemote >>>> Fig assert: "err == 0 " at bail (FigCaptureSourceRemote.m:669) - (err=-16453)
<<<< FigCaptureSourceRemote >>>> Fig assert: "! storage->connectionDied" at bail `

And the crash is not reproducible now.

**Comment by IGitGotIt** [comment]
> @IGitGotIt @juliobecerragomez Did you fix something on your side? I can't see anymore logs
> 
> `<<<< FigCaptureSourceRemote >>>> Fig assert: "! storage->connectionDied" at bail (FigCaptureSourceRemote.m:235) - (err=0) <<<< FigCaptureSourceRemote >>>> Fig assert: "err == 0 " at bail (FigCaptureSourceRemote.m:253) - (err=18 446 744 073 709 535 163) <<<< FigCaptureSourceRemote >>>> Fig assert: "err == 0 " at bail (FigCaptureSourceRemote.m:669) - (err=-16453) <<<< FigCaptureSourceRemote >>>> Fig assert: "! storage->connectionDied" at bail `
> 
> And the crash is not reproducible now.

That's good. No we did not do anything. Did you restart the phone ?

**Comment by GlebPBanuba** [comment]
@IGitGotIt how does restarting phone impact on the crash? 
As you know we cannot ask users to restart the phone before opening the feature Live Stream.

**Comment by IGitGotIt** [comment]
> @IGitGotIt how does restarting phone impact on the crash? As you know we cannot ask users to restart the phone before opening the feature Live Stream.

I was just asking "was the reason you are not seeing any crashes NOW, was because you restarted the phone or not".
Nobody recommends what you are saying as a solution, btw.

**Comment by IGitGotIt** [comment]
Is the issue fixed now, since  you are not seeing any more crashes. 
Thanks

**Comment by GlebPBanuba** [comment]
@IGitGotIt , we are still experiencing the same crash in our build and cannot release the app.

**Comment by IGitGotIt** [comment]
> @IGitGotIt , we are still experiencing the same crash in our build and cannot release the app.

I am confused by conflicting messages about crashes happening and not happening here and I have not been able to repo the crash with the original sample code.

Anyway did you try our previous "experimental" recommendation  https://github.com/opentok/opentok-ios-sdk-samples/issues/304#issuecomment-1889903694 . What was the result?

Thanks
